name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22' # Usa la versione di Node.js che preferisci
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run npm audit (Security Scan)
      run: npm audit --audit-level=moderate
      continue-on-error: true # Permette al workflow di continuare anche con avvisi di audit

    - name: Run ESLint (Code Quality)
      run: npm run lint

    - name: Run TypeScript Check (Type Safety)
      run: npm run tsc --noEmit

    - name: Run Tests (Stability)
      run: npm test

  codeql:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: javascript

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
